### ISSUE TITLE
Function ApiClient.getPlayers() does not work

### ISSUE THREAD

**Issue by Tetraquark** [kevcodez/pubg-api-kotlin#7]
I tried to get a player by name like this:

```kotlin
val playersResponse = apiClient.getPlayers(Region.PC_EUROPE, PlayerFilter(playerNames = listOf("tetraquark")))
```

And got exception:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (START_OBJECT), expected VALUE_STRING: need JSON String that contains type id (for subtype of de.kevcodez.pubg.model.player.PlayerType)
...
at de.kevcodez.pubg.client.ApiClient.getPlayers(ApiClient.kt:74)
```

The API response body contained JSON string like this:

```
{
"data":[
	{
	"type":"...",
	"id":"...",
	"attributes": {...},
	"relationships":{...},
	"links":{...}
	}
],
"links":{...},
"meta":{}
}
```

, where `data` actually is an array, but the mapper trying parse that field as json property.

And a related question. There is the example of code in the README:

```kotlin
val playerResponse = apiClient.getPlayers(Region.PC_EUROPE, ApiClient.PlayerFilter(playerNames = listOf("HazeZombie")))
playerResponse.players.forEach { 
    println(it.id)
}
```

In the current version of the wrapper:

1. Class `PlayerFilter` is not a inner class of `ApiClient`.
2. `PlayerResponse` data class doesn't contain a field `players`

So, how to correctly get a player or many players by name?

**Comment by kevcodez** [comment]
Thanks for reporting this issue!

I found two issues:

1. The API responds with different structures for getPlayer / getPlayers endpoints. GetPlayers actually returns an array within data.

2. When searching for multiple names, they are joined to a single string and added as query parameter. Rather than joining with a single comma, a whitespace was included aswell.

I fixed both issues and released version 0.2.1. The version should be available with maven central within the next minutes.

I also edited the README and included a valid example.
